apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-07-17T13:26:22Z"
deprecatedLastTimestamp: "2024-07-17T13:26:22Z"
deprecatedSource:
  component: default-scheduler
eventTime: null
kind: Event
metadata:
  name: local-path-provisioner-6bc4bddd6b-qcgwl.17e3030061cc58c4
  namespace: local-path-storage
note: Successfully assigned local-path-storage/local-path-provisioner-6bc4bddd6b-qcgwl
  to testkind-control-plane
reason: Scheduled
regarding:
  apiVersion: v1
  kind: Pod
  name: local-path-provisioner-6bc4bddd6b-qcgwl
  namespace: local-path-storage
  resourceVersion: "375"
  uid: a5e3ed7f-8a8a-4386-93f4-c5105c871344
type: Normal
