apiVersion: v1
data:
  jws-kubeconfig-abcdef: eyJhbGciOiJIUzI1NiIsImtpZCI6ImFiY2RlZiJ9..WX8JWZxAMT5Iy_RvpUJaLY1mSigNVDh5x8Om8SB0xsk
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1EY3hOekV6TWpVMU1Gb1hEVE0wTURjeE5URXpNalUxTUZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTU5uCnRoVjhIRGhTU1hGSGNTc2xvVTR0Y3dJVjhiOEdmR09aT0lRUFpWclBmM1NpVkxIQXZXV0RPWW9Odm9Dc1Z6WTYKN3lhSkltS2kvclFpd0ZBbkp4TEhJQnNxRzhoNXp6VGRjUURuSzNkQjVmSkNDTTJtNXltMlhzUkp2cEJaOVF1eQpxY0NJODBTZTNPZ3hhV0V6ZmZvQVRXU0JWYVFPSkM0dDBjZ3ZQdlhCZEhtRW9IdG5URlF0eVBaTFBmMU00L0liCmg1YUdtdHJSN0ZYd1pKU0NkN0JHWkVYc2tXVXpTdk51RkUxaGQyRTVPLzZ0dGt1ZzdTY1lVN21FSWx1TVhlMFgKeVIrVHRBbkVyTWFiZlFKaGh4R1o1SjZybWh4d2lYNCtoVms2TCtORXEvRVNTWGlleUUyYldNOE4zODZlZDl6ZQpodFFlbE5BRFJQMlpxOHl5ck1rQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZFYlh4ZGJtTWxITVRRY3o1R2RjbExxNEdmanhNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQjZpWkZyUy85RXk1ZXREVFg3bAp1S2Z3bjE2cDVXaEtJeVowaTcvTVYxVGxzUmw0N0ZIcGlYdDYycVFKalhUazFwcURYWExzL3I5V2x2Z0djMjh4CkpvOEJoY01GK0l1NkVHMnhHUWxxUFBlT21lYnk3SkRIeWZEeGNoQ0RkOTljaDVYTXN1ZFlOWlc0bldtU1g3RmcKRkF5c2NsT1hYUUNXb3l1WUVxQVJvYUQ2Z21tVVR1M2k3ZzFYRTVPNTRWeDREamNNWEVGR0I5S2tCQUZOeGRqRwo1WXc2cmo4QXMzbFd0Z2Q3bDZ3NGlVemlvd2JmYisrS2JTZC9DSmR1MmpReWdHa216U0FRL1YzY2k2Z3RHdmdFCjFxK3JiUm51bmJBWFFCWUk2ZXdlVlRzT09UWHNGNTczZlFlWlcrRFZnMXFLeVUxUlhaTCszQWc1aDRtcXBsbUcKNjljPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://testkind-control-plane:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
