apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-07-17T13:26:25Z"
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.244.0.2
    nodeName: testkind-control-plane
    targetRef:
      kind: Pod
      name: coredns-5d78c9869d-4xxpr
      namespace: kube-system
      uid: 389aabbe-527b-498b-af72-d29b45109923
  - ip: 10.244.0.3
    nodeName: testkind-control-plane
    targetRef:
      kind: Pod
      name: coredns-5d78c9869d-7qnr9
      namespace: kube-system
      uid: 1efaceb4-1fcf-4720-89ff-06263e1b2e91
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: metrics
    port: 9153
    protocol: TCP
