apiVersion: v1
kind: Pod
metadata:
  labels:
    app: local-path-provisioner
    pod-template-hash: 6bc4bddd6b
  name: local-path-provisioner-6bc4bddd6b-qcgwl
  namespace: local-path-storage
spec:
  containers:
  - command:
    - local-path-provisioner
    - --debug
    - start
    - --helper-image
    - docker.io/kindest/local-path-helper:v20230510-486859a6
    - --config
    - /etc/config/config.json
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    image: docker.io/kindest/local-path-provisioner:v20230511-dc714da8
    name: local-path-provisioner
    volumeMounts:
    - mountPath: /etc/config/
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-r765l
      readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  serviceAccountName: local-path-provisioner-service-account
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      name: local-path-config
    name: config-volume
  - name: kube-api-access-r765l
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
