apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2024-07-17T13:26:19Z"
deprecatedLastTimestamp: "2024-07-17T13:26:19Z"
deprecatedSource:
  component: replicaset-controller
eventTime: null
kind: Event
metadata:
  name: coredns-5d78c9869d.17e302ffa83ce3d3
  namespace: kube-system
note: 'Created pod: coredns-5d78c9869d-4xxpr'
reason: SuccessfulCreate
regarding:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: coredns-5d78c9869d
  namespace: kube-system
  resourceVersion: "331"
  uid: db2d1d3e-5322-4f26-bb03-3409fe489c5a
type: Normal
